robot:
    interface: ens3
    joint_modules:
        motor_numbers: [0, 3, 2, 1, 5, 4, 6, 9, 8, 7, 11, 10]
        motor_constants: 0.025
        gear_ratios: 9.
        max_currents: 1.
        reverse_polarities: [
            true, false, true, true, false, false,
            true, false, true, true, false, false
        ]
        lower_joint_limits: [
            -1.2, -1.7, -3.4, -1.2, -1.7, -3.4,
            -1.2, -1.7, -3.4, -1.2, -1.7, -3.4
        ]
        upper_joint_limits: [
            1.2,  1.7, +3.4, +1.2, +1.7, +3.4,
            1.2,  1.7, +3.4, +1.2, +1.7, +3.4
        ]
        max_joint_velocities: 80.
        safety_damping: 0.5
    imu:
        rotate_vector: [1, 2, 3]
        orientation_vector: [1, 2, 3, 4]
joint_calibrator:
    # Can be either POS, NEG, ALT or AUTO
    search_methods: [
      AUTO, AUTO, AUTO, AUTO, AUTO, AUTO,
      AUTO, AUTO, AUTO, AUTO, AUTO, AUTO
    ]
    position_offsets: [
        0.184, -0.370, -0.005, -.150,
        0.000,  0.310,  0.165, 0.150,
        0.365, 0.202, -0.175, -0.175
    ]
    Kp: 3.
    Kd: 0.05
    T: 1.
    dt: 0.001
